services:
  - type: web
    name: slav
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    region: frankfurt
    autoDeploy: true
    branch: main
    pullRequestPreviewsEnabled: false
    healthCheckPath: /